application: igdsanglah
service: default
runtime: go
api_version: go1.9

handlers:
- url: /stylesheets
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /static
  static_dir: statics
- url: /templates
  static_dir: templates
  application_readable: true
- url: /createkursor
  script: _go_app
- url: /.*
  login: required
  script: _go_app
  secure: always